F/bgstotem/nav
GiveUsMoney/FanFixiv-user-page pull request #13
Opened 2022-09-25 11:06 UTC by akswnd98

> feat: 상단 nav prototype

- 아직 기능은 들어가지 않았습니다. (레이아웃만)
- 성인 모드 스위치가 nav에 구현 되었습니다.

2022-09-25 12:57 UTC, Roharui approved these changes

2022-09-25 12:57 UTC, Roharui commented on src/components/Nav/index.tsx
> +        <Buttons />
프로필 아이콘 기능은 어디에 있나요?

2022-09-25 18:11 UTC, dalcon10028 requested changes
고생하셨습니다 function 만 확인해주세요

2022-09-25 18:11 UTC, dalcon10028 commented on src/components/Nav/Buttons/AdultSwitch/index.tsx
> +  `;
function 내부는 렌더링마다 동작하는 걸로 알고 있어서 런타임에 변경될 일 없는 값들은 function 밖으로 빠지는게 맞는것 같습니다 위로 뺄지 아래로 뺄지는 의논해보아요

2022-09-25 18:11 UTC, dalcon10028 commented on src/assets/theme/theme.ts
> +    button?: PaletteColorOptions | undefined;
hover, button등등 meaning이 모호해서 지영님이랑 의논해봐야할 것 같아요 책갈피 용으로 남겨둘게요

2022-09-25 18:11 UTC, dalcon10028 commented on src/pages/Home/index.tsx
> +      <Nav />
Nav는 모든 페이지에 보이니(다시 렌더링 되면 안되니) App.tsx에 넣어주세요

2022-09-25 18:11 UTC, dalcon10028 commented on src/components/Nav/Buttons/index.tsx
> +  font-weight: bold;
이건 취향인 것 같아서 의논 해보아요
https://emotion.sh/docs/styled#changing-based-on-props
css={} attribute 없앨 수 있어서

2022-09-25 18:14 UTC, dalcon10028 commented on src/components/Nav/Buttons/index.tsx
> +export default function Buttons() {
이름이 너무 범용적이에요

2022-09-25 18:19 UTC, dalcon10028 commented on src/components/Nav/index.tsx
> +export default function Nav() {
일관되게 fullname을 쓰면 좋겠어요
Navigation or NavigationBar ..

2022-09-25 18:19 UTC, dalcon10028 commented on public/svgs/hash.svg
> +</svg>
icon은 src내에서 사용해야하니 /src/assets 어딘가에 있었으면 좋겠어요

2022-09-26 00:06 UTC, akswnd98 commented on src/components/Nav/Buttons/AdultSwitch/index.tsx
> +  `;
아 맞네요.
한 수 배워갑니다 ㅎㅎ.
성능 부분 고민해보겠습니다.

2022-09-26 00:07 UTC, akswnd98 commented on src/pages/Home/index.tsx
> +      <Nav />
넵

2022-09-26 00:16 UTC, akswnd98 commented on src/components/Nav/Buttons/index.tsx
> +  font-weight: bold;
저도 익숙해서 css={}으로 해서 쓰다가
인터페이스 분리가 styled가 더 좋은거 같아서 (decorator패턴)
왠만하면 styled로 쓰는게 좋을거 같습니다.

2022-09-26 00:17 UTC, akswnd98 commented on src/components/Nav/Buttons/index.tsx
> +export default function Buttons() {
인정합니다.

2022-09-26 00:18 UTC, akswnd98 commented on src/components/Nav/index.tsx
> +        <Buttons />
까먹었습니다.
추가해서 다시 커밋 올리겠습니다.

2022-09-28 17:07 UTC, dalcon10028 approved these changes
고생하셨습니다
스타일은 function 위에 쓰는걸로 정하신것 같아서 맞춰서 변경할게요~
스타일 방식 통일만 부탁드립니다

2022-09-28 17:07 UTC, dalcon10028 commented on src/components/Navigation/Buttons/Avatar/index.tsx
> +import { useState } from 'react';
스타일 적용을 방식을 하나로 좋겠는데 (styled, muiStyled중에 하나만 사용) 
`import { styled } from '@mui/material/styles';` 이거 위주로 사용하는 것 같아서
이걸로 통일하시는건 어떠신가요?

https://mui.com/material-ui/react-slider/#inverted-track

2022-09-30 05:09 UTC, merged