F/bgstotem/#18
GiveUsMoney/FanFixiv-user-page pull request #24
Opened 2022-10-15 09:14 UTC by akswnd98

> #18

**PR 설명**
로그인 기능을 완성하였습니다.
https://giveusmoney.github.io/FanFixiv-user-page/ 에서 테스트 하실 수 있습니다.

**개발된 기능**
- 로그인과 관련된 navigation ui 이슈 제거
- 로그인 기능 (twitter 제외)

**레퍼런스**
- 현재 dev server에 올려둔 상태입니다. https://giveusmoney.github.io/FanFixiv-user-page/

2022-10-16 06:03 UTC, dalcon10028 requested changes
고생하셨습니다 이따 몇가지 의논할 게 있어서 조정 후 반영 부탁드립니다 :)

2022-10-16 06:03 UTC, dalcon10028 commented on src/components/BlockMessage/index.tsx
> +};
이거 이전에는 interface 파일 분리하기로 했던 것 같아서 이거 이따가 다같이 얘기 해요

2022-10-16 06:03 UTC, dalcon10028 commented on src/components/Navigation/Buttons/index.tsx
> +  }, []);
이거는 axios설정 제가 따로 빼놔서 이것도 이따가 같이 이야기 해보아요

2022-10-16 06:03 UTC, dalcon10028 commented on src/index.tsx
> +  );
요거 위치도 같이 고민해 보아요

2022-10-16 06:03 UTC, dalcon10028 commented on src/states/avatarDrawer/index.ts
> +});
요거는 props 를 안쓰고 분리하신 이유가 몬가여?

2022-10-26 08:34 UTC, Roharui approved these changes
로그인 이후 19금 Switch 표시와 Drawer 그림자 추가되었나요?

2022-10-26 08:34 UTC, Roharui commented on src/pages/twitter/login/index.tsx
> +    location.href = '/';
이 부분을 `REACT_APP_PUBLIC_URL`로 바꿔야 할듯합니다.

2022-10-26 08:34 UTC, Roharui commented on src/components/layout/Navigation/Drawer/Items/Empty/index.tsx
> +import theme from '../../../../../../assets/theme/theme';
이 부분 `@src`로 고칠수는 없나요?

2022-10-26 08:34 UTC, Roharui commented on src/apis/userApi.ts
> +        id: email,
`id`라고 되어있는데 백엔드에서 `email`로 고칠수 있습니다. 헷갈릴 여지가 있다면 바꿔 드리겠습니다.

2022-10-27 03:33 UTC, akswnd98 commented on src/components/layout/Navigation/Drawer/Items/Empty/index.tsx
> +import theme from '../../../../../../assets/theme/theme';
6중은 좀 심했네요.
@assets로 바꾸겠습니다.

2022-10-27 03:35 UTC, akswnd98 commented on src/apis/userApi.ts
> +        id: email,
email만 있으니까 email로 갔으면 좋겠습니다.

2022-11-07 01:03 UTC, merged